_target_: pytorch_lightning.Trainer

min_epochs: 1
max_epochs: 9999999
enable_progress_bar: True
gradient_clip_val: 1
precision: 32
check_val_every_n_epoch: 1
accelerator: auto
devices: auto
num_nodes: 1

# Interpolated
default_root_dir: ${paths.full_path}
