_target_: src.models.ct.ConsistancyTrainedDenoiser

use_ctxt: False
use_ctxt_img: False
loss_name: mse
min_sigma: 0.002
max_sigma: 80
ema_sync: 0.999
p_mean: -1.2
p_std: 1.2
n_gen_steps: 3

# Noise schedule for the generation
sigma_function:
  _target_: mattstools.mattstools.k_diffusion.get_sigmas_karras
  _partial_: True
  n_steps: 20
  rho: 7

cosine_config:
  outp_dim: 64
  frequency_scaling: exponential

normaliser_config:
  max_n: 100_000

# Full UNet Model
unet_config:
  min_size: 4
  attn_below: 8
  start_channels: 64
  max_channels: 256
  zero_out: False
  resnet_config:
    act: silu
    drp: 0.1
    nrm_groups: 16
  attn_config:
    num_heads: 16
    nrm_groups: 8
    do_pos_encoding: True

  ctxt_embed_config:
    act_h: silu
    hddn_dim: 128
    num_blocks: 2
    nrm: layer

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.RAdam
  _partial_: true
  lr: 5.0e-5
  weight_decay: 0

# Config dicts to pass to mattstools and pytorch lightning
sched_config:
  mattstools:
    name: warmup
    num_steps: 1000
  lightning:
    monitor: valid/total_loss
    interval: step
    frequency: 1
