_target_: src.models.diffusion.ImageDiffusionGenerator

use_ctxt: False
loss_name: mse
min_time: 0
max_time: 80
ema_sync: 0.999
p_mean: -1.2
p_std: 1.2

sampler_name: heun
sampler_steps: 50
sampler_min_time: 1.0e-3
sampler_curvature: 7

cosine_config:
  outp_dim: 16
  frequency_scaling: exponential

normaliser_config:
  max_n: 100_000

# Full UNet Model
unet_config:
  min_size: 8
  attn_below: 16
  start_channels: 32
  max_channels: 128
  resnet_config:
    act: lrlu
    drp: 0
    nrm_groups: 4
  attn_config:
    num_heads: 4
    nrm_groups: 4
  ctxt_embed_config:
    hddn_dim: 128
    num_blocks: 2
    nrm: layer

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 5.0e-4
  weight_decay: 0

# Config dicts to pass to mattstools and pytorch lightning
sched_config:
  mattstools:
    name: warmup
    num_steps: 10000
  lightning:
    monitor: valid/total_loss
    interval: step
    frequency: 1
