_target_: src.models.diffusion.ImageDiffusionGenerator

use_ctxt: False
use_ctxt_img: False
loss_name: mse
min_sigma: 0.002
max_sigma: 80
ema_sync: 0.999
p_mean: -1.2
p_std: 1.2

# Sampler and noise schedule for the generation
sampler_function:
  _target_: mattstools.mattstools.k_diffusion.sample_heun
  _partial_: True

sigma_function:
  _target_: mattstools.mattstools.k_diffusion.get_sigmas_karras
  _partial_: True
  n_steps: 100
  rho: 7

cosine_config:
  outp_dim: 32
  frequency_scaling: exponential

normaliser_config:
  max_n: 100_000

# Full UNet Model
unet_config:
  min_size: 8
  attn_below: 16
  start_channels: 128
  max_channels: 256
  zero_out: False
  n_blocks_per_layer: 1

  resnet_config:
    act: silu
    drp: 0
    nrm_groups: 8

  attn_config:
    num_heads: 8
    nrm_groups: 8
    do_pos_encoding: True

  ctxt_embed_config:
    hddn_dim: 256
    outp_dim: 256
    num_blocks: 1
    act_h: silu
    act_o: silu
    nrm: layer

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1.0e-4
  weight_decay: 0

# Config dicts to pass to mattstools and pytorch lightning
sched_config:
  mattstools:
    name: warmup
    num_steps: 2_00_000
  lightning:
    monitor: valid/total_loss
    interval: step
    frequency: 1
