base_kwargs:
  device: gpu
  name: DiffusionSuperResolution
  save_dir: /home/matthew/Documents/saved_networks
  net_type: unet

n_timesteps: 500
loss_name: mse
time_embedding_dim: 8
upscale_factor: 8
unet_kwargs:
  min_size: 4
  attn_after: 3
  start_channels: 16
  max_channels: 128
  resnet_kwargs:
    dims: 2
    act: lrlu
    drp: 0.1
    nrm_groups: 1
  attn_kwargs:
    num_heads: 1
    nrm_groups: 1
time_embed_kwargs:
  num_blocks: 2
  hddn_dim: 64
