base_kwargs:
  device: gpu
  name: UNetGANUpscaler
  save_dir: /home/matthew/Documents/saved_networks
  net_type: unet-gan

gan_mode: lsgan

unet_kwargs:
  min_size: 4
  attn_after: 3
  start_channels: 16
  max_channels: 128
  resnet_kwargs:
    dims: 2
    act: lrlu
    drp: 0.1
    nrm_groups: 4
  attn_kwargs:
    num_heads: 4
    nrm_groups: 4

disc_kwargs:
  outp_size: 32
  start_channels: 8
  max_channels: 32
  resnet_kwargs:
    dims: 2
    act: lrlu
    drp: 0.1
    nrm_groups: 8

optim_dict:
  name: adam
  lr: 5.0e-4

sched_dict:
  name: warmup
  num_steps: 512
