base_kwargs:
  device: gpu
  name: DiffusionSuperResolution
  save_dir: /home/users/l/leighm/scratch/Saved_Networks/ImageProcessing
  net_type: unet

loss_name: mae
time_embedding_dim: 8
upscale_factor: 8
unet_kwargs:
  min_size: 4
  attn_after: 18
  start_channels: 8
  max_channels: 32
  resnet_kwargs:
    dims: 2
    act: lrlu
    drp: 0.1
    nrm_groups: 1
  attn_kwargs:
    num_heads: 1
    nrm_groups: 1
time_embed_kwargs:
  num_blocks: 2
  hddn_dim: 64
