base_kwargs:
  device: gpu
  name: UNetUpscaler2
  save_dir: /home/matthew/Documents/saved_networks
  net_type: unet

unet_kwargs:
  min_size: 4
  attn_after: 3
  start_channels: 32
  max_channels: 128
  resnet_kwargs:
    act: lrlu
    drp: 0.1
    nrm_groups: 32
  attn_kwargs:
    num_heads: 4
    nrm_groups: 32

