_target_: src.datamodules.images.ImageDataModule
_convert_: object

train_set:
  _target_: src.datamodules.images.ImageUpscaleDataset
  _partial_: True
  factor: ${upscale_factor}
  dataset:
    _target_: torchvision.datasets.ImageFolder
    _partial_: True
    root: ${paths.data_dir}/afhq_v2/train
    transform:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.RandomHorizontalFlip
        - _target_: torchvision.transforms.RandomResizedCrop
          antialias: True
          size: ${resize}
          scale: [0.6, 1]
          ratio: [0.9, 1.1]
        - _target_: torchvision.transforms.ToTensor

test_set:
  _target_: ${..train_set._target_}
  _partial_: True
  factor: ${..train_set.factor}
  dataset:
    _target_: ${...train_set.dataset._target_}
    _partial_: True
    root: ${paths.data_dir}/afhq_v2/test
    transform:
      _target_: torchvision.transforms.Compose
      transforms:
        - _target_: torchvision.transforms.Resize
          size: ${resize}
          antialias: True
        - _target_: torchvision.transforms.ToTensor

loader_config:
  pin_memory: true
  batch_size: 64
  num_workers: 8
  drop_last: True
  shuffle: True
