_target_: src.datamodules.images.ImageDataModule
_convert_: object

train_set:
  _target_: torchvision.datasets.CelebA
  _partial_: True
  root: ${paths.data_dir}
  split: train
  target_type: attr
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.PILToTensor
      - _target_: torchvision.transforms.Resize
        size: ${resize}
        antialias: False
      - _target_: torchvision.transforms.CenterCrop
        size: ${crop_size}
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ConvertImageDtype
        dtype:
          _target_: mattstools.mattstools.torch_utils.dtype_lookup
          dtype: float

test_set:
  _target_: ${..train_set._target_}
  _partial_: True
  split: test
  root: ${paths.data_dir}
  target_type: ${..train_set.target_type}
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.PILToTensor
      - _target_: torchvision.transforms.Resize
        size: ${resize}
        antialias: False
      - _target_: torchvision.transforms.CenterCrop
        size: ${crop_size}
      - _target_: torchvision.transforms.ConvertImageDtype
        dtype:
          _target_: mattstools.mattstools.torch_utils.dtype_lookup
          dtype: float

loader_config:
  pin_memory: true
  batch_size: 256
  num_workers: 8
  drop_last: True
  shuffle: True
