_target_: src.datamodules.images.ImageDataModule
_convert_: object

train_set:
  _target_: torchvision.datasets.FashionMNIST
  _partial_: True
  root: ${paths.data_dir}
  train: True
  download: True
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.PILToTensor
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ConvertImageDtype
        dtype:
          _target_: mattstools.mattstools.torch_utils.dtype_lookup
          dtype: float


test_set:
  _target_: torchvision.datasets.FashionMNIST
  _partial_: True
  root: ${paths.data_dir}
  train: False
  download: True
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.PILToTensor
      - _target_: torchvision.transforms.ConvertImageDtype
        dtype:
          _target_: mattstools.mattstools.torch_utils.dtype_lookup
          dtype: float

loader_config:
  pin_memory: true
  batch_size: 32
  num_workers: 8
  drop_last: True
  shuffle: True
